# Generated by Django 3.0.3 on 2020-02-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200215_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
