# Generated by Django 3.0.3 on 2020-02-16 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_post_book_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stars',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
